[package]
name = "dihardts_omicstools"
version = "1.4.0"
edition = "2021"
readme = "Readme.md"
description = "Collection of different omic tools, structs and enums."
repository = "https://github.com/di-hardt/omicstools.git"
homepage = "https://github.com/di-hardt/omicstools.git"
documentation = "https://github.com/di-hardt/omicstools.git"
license-file = "LICENSE"

[dependencies]
anyhow = "1.0.72"

[build-dependencies]
anyhow = "1.0.72"
askama = "0.12.0"
csv = "1.2.2"
